# Generated by Django 5.1.1 on 2024-09-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='preacher',
            field=models.CharField(default='Justus Mutuku', max_length=255),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='preacher_number',
            field=models.CharField(default='0717740400', max_length=30),
        ),
    ]
