# Generated by Django 5.1.1 on 2024-09-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_sermon_preacher_alter_sermon_preacher_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='preacher_profile_pic',
            field=models.ImageField(default='static/assets/user.png', upload_to='preacher-profile-pics'),
        ),
    ]
