# Generated by Django 5.1.1 on 2024-09-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_sermon_preacher_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
