# Generated by Django 5.1.1 on 2024-09-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('profile_pic', models.ImageField(upload_to='leader-profile-pics')),
                ('department', models.CharField(max_length=255)),
            ],
        ),
    ]
