# Generated by Django 5.1.1 on 2024-09-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_churchleader'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchleader',
            name='specification',
            field=models.CharField(default='Head of Department', max_length=255),
        ),
    ]
